version: '3.8'

services:
  app-torch:  # app name
    build: .  # build from the current directory
    image: pytorch-lab-img
    container_name: pytorch-container  # container name

    # mapping current directory to /app in the container
    volumes:
      - .:/app

    # mapping port 8888 of the container to port 8888 of the host
    ports:
      - "8888:8888"


    # --ip=0.0.0.0: allows access from any IP address
    # --allow-root: Docker acts as root, Jupyter forbids running as root by default
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root