version: '3.8'

services:
  app-torch-gpu:
    build:
      context: .
      dockerfile: Dockerfile
    image: pytorch-lab-gpu
    container_name: pytorch-gpu-container



    volumes:
      - .:/app

    ports:
      - "8888:8888"

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # select all available GPUs (or 1)
              capabilities: [gpu]

    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root